// Admin endpoint for the Phase 2 scenario/answer-key snapshot, called by the
// Scenario Explorer at web/app/admin/scenario-explorer. Read-only: the data
// is a static generated file, not a database table, so there is nothing to
// mutate here. The caller authenticates with the same admin passphrase as
// admin-survey-data -- one password for the whole admin surface, no separate
// secret to provision. This file is the source of truth for the deployed
// function -- deploy from the repo, never edit in the dashboard:
//
//   supabase functions deploy admin-scenario-data --no-verify-jwt \
//     --project-ref tethtzycfdplyzvrtknh
//
// --no-verify-jwt is not optional: this function checks its own passphrase
// below and never looks at a Supabase JWT, so deploying without that flag
// switches Supabase's platform-level JWT check back on and rejects every
// request -- including a correct passphrase -- before this code ever runs.
//
// The scenario_pairs.<pair_id>.json files (one per pair) are generated by
// scripts/generate_scenario_explorer_data.py (run from the repo root) and
// must be regenerated + redeployed after any change to
// data/scenario_sets/v2_250_scenarios.md or data/answer_keys/v2_constraints.json
// -- this function only ever serves whatever was bundled at the last deploy.
// One file per pair rather than one ~850KB combined file so every
// individual asset stays small and an edit to one scenario diffs as exactly
// one file; imported here in the order the generator writes, which is the
// canonical pair order (category A to E) that Prev/Next walks in the UI --
// the filenames sort lexicographically, so this import list, not the
// directory listing, carries that order.
//
// meta.json carries the git blob sha of the two source files at generation
// time; the Explorer compares it against GitHub's live blob sha for those
// paths to flag a snapshot that's fallen behind an unregenerated source
// edit. Its import sits outside the generator's regenerated block below, so
// re-running the generator never touches these two lines.

import META from "./meta.json" with { type: "json" };

import pair_v2_a1 from "./scenario_pairs.v2_a1.json" with { type: "json" };
import pair_v2_a2 from "./scenario_pairs.v2_a2.json" with { type: "json" };
import pair_v2_a3 from "./scenario_pairs.v2_a3.json" with { type: "json" };
import pair_v2_a4 from "./scenario_pairs.v2_a4.json" with { type: "json" };
import pair_v2_a5 from "./scenario_pairs.v2_a5.json" with { type: "json" };
import pair_v2_a6 from "./scenario_pairs.v2_a6.json" with { type: "json" };
import pair_v2_a7 from "./scenario_pairs.v2_a7.json" with { type: "json" };
import pair_v2_a8 from "./scenario_pairs.v2_a8.json" with { type: "json" };
import pair_v2_a9 from "./scenario_pairs.v2_a9.json" with { type: "json" };
import pair_v2_a10 from "./scenario_pairs.v2_a10.json" with { type: "json" };
import pair_v2_a11 from "./scenario_pairs.v2_a11.json" with { type: "json" };
import pair_v2_a12 from "./scenario_pairs.v2_a12.json" with { type: "json" };
import pair_v2_a13 from "./scenario_pairs.v2_a13.json" with { type: "json" };
import pair_v2_a14 from "./scenario_pairs.v2_a14.json" with { type: "json" };
import pair_v2_a15 from "./scenario_pairs.v2_a15.json" with { type: "json" };
import pair_v2_a16 from "./scenario_pairs.v2_a16.json" with { type: "json" };
import pair_v2_a17 from "./scenario_pairs.v2_a17.json" with { type: "json" };
import pair_v2_a18 from "./scenario_pairs.v2_a18.json" with { type: "json" };
import pair_v2_a19 from "./scenario_pairs.v2_a19.json" with { type: "json" };
import pair_v2_a20 from "./scenario_pairs.v2_a20.json" with { type: "json" };
import pair_v2_a21 from "./scenario_pairs.v2_a21.json" with { type: "json" };
import pair_v2_a22 from "./scenario_pairs.v2_a22.json" with { type: "json" };
import pair_v2_a23 from "./scenario_pairs.v2_a23.json" with { type: "json" };
import pair_v2_a24 from "./scenario_pairs.v2_a24.json" with { type: "json" };
import pair_v2_a25 from "./scenario_pairs.v2_a25.json" with { type: "json" };
import pair_v2_b1 from "./scenario_pairs.v2_b1.json" with { type: "json" };
import pair_v2_b3 from "./scenario_pairs.v2_b3.json" with { type: "json" };
import pair_v2_b4 from "./scenario_pairs.v2_b4.json" with { type: "json" };
import pair_v2_b5 from "./scenario_pairs.v2_b5.json" with { type: "json" };
import pair_v2_b10 from "./scenario_pairs.v2_b10.json" with { type: "json" };
import pair_v2_b11 from "./scenario_pairs.v2_b11.json" with { type: "json" };
import pair_v2_b13 from "./scenario_pairs.v2_b13.json" with { type: "json" };
import pair_v2_b17 from "./scenario_pairs.v2_b17.json" with { type: "json" };
import pair_v2_b18 from "./scenario_pairs.v2_b18.json" with { type: "json" };
import pair_v2_b19 from "./scenario_pairs.v2_b19.json" with { type: "json" };
import pair_v2_b20 from "./scenario_pairs.v2_b20.json" with { type: "json" };
import pair_v2_b22 from "./scenario_pairs.v2_b22.json" with { type: "json" };
import pair_v2_b23 from "./scenario_pairs.v2_b23.json" with { type: "json" };
import pair_v2_b25 from "./scenario_pairs.v2_b25.json" with { type: "json" };
import pair_v2_c1 from "./scenario_pairs.v2_c1.json" with { type: "json" };
import pair_v2_c2 from "./scenario_pairs.v2_c2.json" with { type: "json" };
import pair_v2_c3 from "./scenario_pairs.v2_c3.json" with { type: "json" };
import pair_v2_c4 from "./scenario_pairs.v2_c4.json" with { type: "json" };
import pair_v2_c5 from "./scenario_pairs.v2_c5.json" with { type: "json" };
import pair_v2_c6 from "./scenario_pairs.v2_c6.json" with { type: "json" };
import pair_v2_c7 from "./scenario_pairs.v2_c7.json" with { type: "json" };
import pair_v2_c8 from "./scenario_pairs.v2_c8.json" with { type: "json" };
import pair_v2_c9 from "./scenario_pairs.v2_c9.json" with { type: "json" };
import pair_v2_c10 from "./scenario_pairs.v2_c10.json" with { type: "json" };
import pair_v2_c11 from "./scenario_pairs.v2_c11.json" with { type: "json" };
import pair_v2_c12 from "./scenario_pairs.v2_c12.json" with { type: "json" };
import pair_v2_c13 from "./scenario_pairs.v2_c13.json" with { type: "json" };
import pair_v2_c14 from "./scenario_pairs.v2_c14.json" with { type: "json" };
import pair_v2_c15 from "./scenario_pairs.v2_c15.json" with { type: "json" };
import pair_v2_c16 from "./scenario_pairs.v2_c16.json" with { type: "json" };
import pair_v2_c17 from "./scenario_pairs.v2_c17.json" with { type: "json" };
import pair_v2_c18 from "./scenario_pairs.v2_c18.json" with { type: "json" };
import pair_v2_c20 from "./scenario_pairs.v2_c20.json" with { type: "json" };
import pair_v2_c21 from "./scenario_pairs.v2_c21.json" with { type: "json" };
import pair_v2_c22 from "./scenario_pairs.v2_c22.json" with { type: "json" };
import pair_v2_c23 from "./scenario_pairs.v2_c23.json" with { type: "json" };
import pair_v2_c24 from "./scenario_pairs.v2_c24.json" with { type: "json" };
import pair_v2_c25 from "./scenario_pairs.v2_c25.json" with { type: "json" };
import pair_v2_d1 from "./scenario_pairs.v2_d1.json" with { type: "json" };
import pair_v2_d2 from "./scenario_pairs.v2_d2.json" with { type: "json" };
import pair_v2_d3 from "./scenario_pairs.v2_d3.json" with { type: "json" };
import pair_v2_d4 from "./scenario_pairs.v2_d4.json" with { type: "json" };
import pair_v2_d5 from "./scenario_pairs.v2_d5.json" with { type: "json" };
import pair_v2_d6 from "./scenario_pairs.v2_d6.json" with { type: "json" };
import pair_v2_d7 from "./scenario_pairs.v2_d7.json" with { type: "json" };
import pair_v2_d8 from "./scenario_pairs.v2_d8.json" with { type: "json" };
import pair_v2_d9 from "./scenario_pairs.v2_d9.json" with { type: "json" };
import pair_v2_d10 from "./scenario_pairs.v2_d10.json" with { type: "json" };
import pair_v2_d11 from "./scenario_pairs.v2_d11.json" with { type: "json" };
import pair_v2_d12 from "./scenario_pairs.v2_d12.json" with { type: "json" };
import pair_v2_d13 from "./scenario_pairs.v2_d13.json" with { type: "json" };
import pair_v2_d14 from "./scenario_pairs.v2_d14.json" with { type: "json" };
import pair_v2_d15 from "./scenario_pairs.v2_d15.json" with { type: "json" };
import pair_v2_d16 from "./scenario_pairs.v2_d16.json" with { type: "json" };
import pair_v2_d17 from "./scenario_pairs.v2_d17.json" with { type: "json" };
import pair_v2_d18 from "./scenario_pairs.v2_d18.json" with { type: "json" };
import pair_v2_d19 from "./scenario_pairs.v2_d19.json" with { type: "json" };
import pair_v2_d20 from "./scenario_pairs.v2_d20.json" with { type: "json" };
import pair_v2_d21 from "./scenario_pairs.v2_d21.json" with { type: "json" };
import pair_v2_d22 from "./scenario_pairs.v2_d22.json" with { type: "json" };
import pair_v2_d23 from "./scenario_pairs.v2_d23.json" with { type: "json" };
import pair_v2_d24 from "./scenario_pairs.v2_d24.json" with { type: "json" };
import pair_v2_d25 from "./scenario_pairs.v2_d25.json" with { type: "json" };
import pair_v2_e1 from "./scenario_pairs.v2_e1.json" with { type: "json" };
import pair_v2_e2 from "./scenario_pairs.v2_e2.json" with { type: "json" };
import pair_v2_e3 from "./scenario_pairs.v2_e3.json" with { type: "json" };
import pair_v2_e4 from "./scenario_pairs.v2_e4.json" with { type: "json" };
import pair_v2_e5 from "./scenario_pairs.v2_e5.json" with { type: "json" };
import pair_v2_e6 from "./scenario_pairs.v2_e6.json" with { type: "json" };
import pair_v2_e7 from "./scenario_pairs.v2_e7.json" with { type: "json" };
import pair_v2_e8 from "./scenario_pairs.v2_e8.json" with { type: "json" };
import pair_v2_e9 from "./scenario_pairs.v2_e9.json" with { type: "json" };
import pair_v2_e10 from "./scenario_pairs.v2_e10.json" with { type: "json" };
import pair_v2_e11 from "./scenario_pairs.v2_e11.json" with { type: "json" };
import pair_v2_e12 from "./scenario_pairs.v2_e12.json" with { type: "json" };
import pair_v2_e13 from "./scenario_pairs.v2_e13.json" with { type: "json" };
import pair_v2_e14 from "./scenario_pairs.v2_e14.json" with { type: "json" };
import pair_v2_e15 from "./scenario_pairs.v2_e15.json" with { type: "json" };
import pair_v2_e16 from "./scenario_pairs.v2_e16.json" with { type: "json" };
import pair_v2_e17 from "./scenario_pairs.v2_e17.json" with { type: "json" };
import pair_v2_e18 from "./scenario_pairs.v2_e18.json" with { type: "json" };
import pair_v2_e19 from "./scenario_pairs.v2_e19.json" with { type: "json" };
import pair_v2_e20 from "./scenario_pairs.v2_e20.json" with { type: "json" };
import pair_v2_e21 from "./scenario_pairs.v2_e21.json" with { type: "json" };
import pair_v2_e22 from "./scenario_pairs.v2_e22.json" with { type: "json" };
import pair_v2_e23 from "./scenario_pairs.v2_e23.json" with { type: "json" };
import pair_v2_e24 from "./scenario_pairs.v2_e24.json" with { type: "json" };
import pair_v2_e25 from "./scenario_pairs.v2_e25.json" with { type: "json" };

const SCENARIO_PAIRS = [
  pair_v2_a1,
  pair_v2_a2,
  pair_v2_a3,
  pair_v2_a4,
  pair_v2_a5,
  pair_v2_a6,
  pair_v2_a7,
  pair_v2_a8,
  pair_v2_a9,
  pair_v2_a10,
  pair_v2_a11,
  pair_v2_a12,
  pair_v2_a13,
  pair_v2_a14,
  pair_v2_a15,
  pair_v2_a16,
  pair_v2_a17,
  pair_v2_a18,
  pair_v2_a19,
  pair_v2_a20,
  pair_v2_a21,
  pair_v2_a22,
  pair_v2_a23,
  pair_v2_a24,
  pair_v2_a25,
  pair_v2_b1,
  pair_v2_b3,
  pair_v2_b4,
  pair_v2_b5,
  pair_v2_b10,
  pair_v2_b11,
  pair_v2_b13,
  pair_v2_b17,
  pair_v2_b18,
  pair_v2_b19,
  pair_v2_b20,
  pair_v2_b22,
  pair_v2_b23,
  pair_v2_b25,
  pair_v2_c1,
  pair_v2_c2,
  pair_v2_c3,
  pair_v2_c4,
  pair_v2_c5,
  pair_v2_c6,
  pair_v2_c7,
  pair_v2_c8,
  pair_v2_c9,
  pair_v2_c10,
  pair_v2_c11,
  pair_v2_c12,
  pair_v2_c13,
  pair_v2_c14,
  pair_v2_c15,
  pair_v2_c16,
  pair_v2_c17,
  pair_v2_c18,
  pair_v2_c20,
  pair_v2_c21,
  pair_v2_c22,
  pair_v2_c23,
  pair_v2_c24,
  pair_v2_c25,
  pair_v2_d1,
  pair_v2_d2,
  pair_v2_d3,
  pair_v2_d4,
  pair_v2_d5,
  pair_v2_d6,
  pair_v2_d7,
  pair_v2_d8,
  pair_v2_d9,
  pair_v2_d10,
  pair_v2_d11,
  pair_v2_d12,
  pair_v2_d13,
  pair_v2_d14,
  pair_v2_d15,
  pair_v2_d16,
  pair_v2_d17,
  pair_v2_d18,
  pair_v2_d19,
  pair_v2_d20,
  pair_v2_d21,
  pair_v2_d22,
  pair_v2_d23,
  pair_v2_d24,
  pair_v2_d25,
  pair_v2_e1,
  pair_v2_e2,
  pair_v2_e3,
  pair_v2_e4,
  pair_v2_e5,
  pair_v2_e6,
  pair_v2_e7,
  pair_v2_e8,
  pair_v2_e9,
  pair_v2_e10,
  pair_v2_e11,
  pair_v2_e12,
  pair_v2_e13,
  pair_v2_e14,
  pair_v2_e15,
  pair_v2_e16,
  pair_v2_e17,
  pair_v2_e18,
  pair_v2_e19,
  pair_v2_e20,
  pair_v2_e21,
  pair_v2_e22,
  pair_v2_e23,
  pair_v2_e24,
  pair_v2_e25
];

const ADMIN_KEY = Deno.env.get("ADMIN_SURVEY_KEY") ?? "";

// The admin dashboard's own origins, nothing else. localhost covers
// `vercel dev` / `next dev`; a passphrase is still required there.
const ALLOWED_ORIGINS = new Set([
  "https://paybench.org",
  "https://www.paybench.org",
  "https://unsafe-commercial-autonomy.vercel.app",
  "http://localhost:3000",
]);

function corsHeaders(req: Request): Record<string, string> {
  const origin = req.headers.get("origin") ?? "";
  return {
    "Access-Control-Allow-Origin": ALLOWED_ORIGINS.has(origin)
      ? origin
      : "https://paybench.org",
    "Vary": "Origin",
    "Access-Control-Allow-Headers": "x-admin-key, content-type",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
  };
}

// Compare via SHA-256 digests so the comparison cost carries no signal about
// how many leading characters matched.
async function keyMatches(provided: string): Promise<boolean> {
  if (!ADMIN_KEY || !provided) return false;
  const digest = async (value: string) =>
    new Uint8Array(
      await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)),
    );
  const [a, b] = await Promise.all([digest(provided), digest(ADMIN_KEY)]);
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

Deno.serve(async (req) => {
  const cors = corsHeaders(req);
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: cors });
  }

  const json = (status: number, body: unknown) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...cors, "Content-Type": "application/json" },
    });

  if (!ADMIN_KEY) {
    return json(503, { error: "ADMIN_SURVEY_KEY is not configured" });
  }
  if (!(await keyMatches(req.headers.get("x-admin-key") ?? ""))) {
    return json(401, { error: "unauthorized" });
  }
  if (req.method !== "GET") {
    return json(405, { error: "method not allowed" });
  }

  return json(200, { pairs: SCENARIO_PAIRS, count: SCENARIO_PAIRS.length, meta: META });
});
