// Admin endpoint for the Phase 2 scenario/answer-key snapshot, called by the
// Scenario Explorer at web/app/admin/scenario-explorer. Read-only: the data
// is a static generated file, not a database table, so there is nothing to
// mutate here. The caller authenticates with the same admin passphrase as
// admin-survey-data -- one password for the whole admin surface, no separate
// secret to provision. This file is the source of truth for the deployed
// function -- deploy from the repo, never edit in the dashboard:
//
//   supabase functions deploy admin-scenario-data --no-verify-jwt \
//     --project-ref tethtzycfdplyzvrtknh
//
// The scenario_pairs.NNN.json chunk files are generated by
// scripts/generate_scenario_explorer_data.py (run from the repo root) and
// must be regenerated + redeployed after any change to
// data/scenario_sets/v2_250_scenarios.md or data/answer_keys/v2_constraints.json
// -- this function only ever serves whatever was bundled at the last deploy.
// Split into many small chunks (each a plain array of a few pairs, packed
// by size) rather than one ~850KB combined file so every individual asset
// stays small; imported here in the same numeric order the generator writes
// them in, which preserves the canonical pair order (category A to E) that
// Prev/Next walks in the UI.

import chunk000 from "./scenario_pairs.000.json" with { type: "json" };
import chunk001 from "./scenario_pairs.001.json" with { type: "json" };
import chunk002 from "./scenario_pairs.002.json" with { type: "json" };
import chunk003 from "./scenario_pairs.003.json" with { type: "json" };
import chunk004 from "./scenario_pairs.004.json" with { type: "json" };
import chunk005 from "./scenario_pairs.005.json" with { type: "json" };
import chunk006 from "./scenario_pairs.006.json" with { type: "json" };
import chunk007 from "./scenario_pairs.007.json" with { type: "json" };
import chunk008 from "./scenario_pairs.008.json" with { type: "json" };
import chunk009 from "./scenario_pairs.009.json" with { type: "json" };
import chunk010 from "./scenario_pairs.010.json" with { type: "json" };
import chunk011 from "./scenario_pairs.011.json" with { type: "json" };
import chunk012 from "./scenario_pairs.012.json" with { type: "json" };
import chunk013 from "./scenario_pairs.013.json" with { type: "json" };
import chunk014 from "./scenario_pairs.014.json" with { type: "json" };
import chunk015 from "./scenario_pairs.015.json" with { type: "json" };
import chunk016 from "./scenario_pairs.016.json" with { type: "json" };
import chunk017 from "./scenario_pairs.017.json" with { type: "json" };
import chunk018 from "./scenario_pairs.018.json" with { type: "json" };
import chunk019 from "./scenario_pairs.019.json" with { type: "json" };
import chunk020 from "./scenario_pairs.020.json" with { type: "json" };
import chunk021 from "./scenario_pairs.021.json" with { type: "json" };
import chunk022 from "./scenario_pairs.022.json" with { type: "json" };
import chunk023 from "./scenario_pairs.023.json" with { type: "json" };
import chunk024 from "./scenario_pairs.024.json" with { type: "json" };
import chunk025 from "./scenario_pairs.025.json" with { type: "json" };
import chunk026 from "./scenario_pairs.026.json" with { type: "json" };
import chunk027 from "./scenario_pairs.027.json" with { type: "json" };
import chunk028 from "./scenario_pairs.028.json" with { type: "json" };
import chunk029 from "./scenario_pairs.029.json" with { type: "json" };
import chunk030 from "./scenario_pairs.030.json" with { type: "json" };
import chunk031 from "./scenario_pairs.031.json" with { type: "json" };
import chunk032 from "./scenario_pairs.032.json" with { type: "json" };
import chunk033 from "./scenario_pairs.033.json" with { type: "json" };
import chunk034 from "./scenario_pairs.034.json" with { type: "json" };
import chunk035 from "./scenario_pairs.035.json" with { type: "json" };
import chunk036 from "./scenario_pairs.036.json" with { type: "json" };
import chunk037 from "./scenario_pairs.037.json" with { type: "json" };
import chunk038 from "./scenario_pairs.038.json" with { type: "json" };
import chunk039 from "./scenario_pairs.039.json" with { type: "json" };
import chunk040 from "./scenario_pairs.040.json" with { type: "json" };
import chunk041 from "./scenario_pairs.041.json" with { type: "json" };
import chunk042 from "./scenario_pairs.042.json" with { type: "json" };
import chunk043 from "./scenario_pairs.043.json" with { type: "json" };
import chunk044 from "./scenario_pairs.044.json" with { type: "json" };
import chunk045 from "./scenario_pairs.045.json" with { type: "json" };
import chunk046 from "./scenario_pairs.046.json" with { type: "json" };
import chunk047 from "./scenario_pairs.047.json" with { type: "json" };
import chunk048 from "./scenario_pairs.048.json" with { type: "json" };
import chunk049 from "./scenario_pairs.049.json" with { type: "json" };
import chunk050 from "./scenario_pairs.050.json" with { type: "json" };
import chunk051 from "./scenario_pairs.051.json" with { type: "json" };
import chunk052 from "./scenario_pairs.052.json" with { type: "json" };
import chunk053 from "./scenario_pairs.053.json" with { type: "json" };
import chunk054 from "./scenario_pairs.054.json" with { type: "json" };
import chunk055 from "./scenario_pairs.055.json" with { type: "json" };
import chunk056 from "./scenario_pairs.056.json" with { type: "json" };
import chunk057 from "./scenario_pairs.057.json" with { type: "json" };
import chunk058 from "./scenario_pairs.058.json" with { type: "json" };
import chunk059 from "./scenario_pairs.059.json" with { type: "json" };
import chunk060 from "./scenario_pairs.060.json" with { type: "json" };
import chunk061 from "./scenario_pairs.061.json" with { type: "json" };
import chunk062 from "./scenario_pairs.062.json" with { type: "json" };
import chunk063 from "./scenario_pairs.063.json" with { type: "json" };
import chunk064 from "./scenario_pairs.064.json" with { type: "json" };
import chunk065 from "./scenario_pairs.065.json" with { type: "json" };
import chunk066 from "./scenario_pairs.066.json" with { type: "json" };
import chunk067 from "./scenario_pairs.067.json" with { type: "json" };
import chunk068 from "./scenario_pairs.068.json" with { type: "json" };
import chunk069 from "./scenario_pairs.069.json" with { type: "json" };
import chunk070 from "./scenario_pairs.070.json" with { type: "json" };
import chunk071 from "./scenario_pairs.071.json" with { type: "json" };
import chunk072 from "./scenario_pairs.072.json" with { type: "json" };
import chunk073 from "./scenario_pairs.073.json" with { type: "json" };
import chunk074 from "./scenario_pairs.074.json" with { type: "json" };
import chunk075 from "./scenario_pairs.075.json" with { type: "json" };
import chunk076 from "./scenario_pairs.076.json" with { type: "json" };
import chunk077 from "./scenario_pairs.077.json" with { type: "json" };
import chunk078 from "./scenario_pairs.078.json" with { type: "json" };
import chunk079 from "./scenario_pairs.079.json" with { type: "json" };
import chunk080 from "./scenario_pairs.080.json" with { type: "json" };
import chunk081 from "./scenario_pairs.081.json" with { type: "json" };
import chunk082 from "./scenario_pairs.082.json" with { type: "json" };
import chunk083 from "./scenario_pairs.083.json" with { type: "json" };
import chunk084 from "./scenario_pairs.084.json" with { type: "json" };
import chunk085 from "./scenario_pairs.085.json" with { type: "json" };
import chunk086 from "./scenario_pairs.086.json" with { type: "json" };
import chunk087 from "./scenario_pairs.087.json" with { type: "json" };
import chunk088 from "./scenario_pairs.088.json" with { type: "json" };
import chunk089 from "./scenario_pairs.089.json" with { type: "json" };
import chunk090 from "./scenario_pairs.090.json" with { type: "json" };

const SCENARIO_PAIRS = [
  ...chunk000,
  ...chunk001,
  ...chunk002,
  ...chunk003,
  ...chunk004,
  ...chunk005,
  ...chunk006,
  ...chunk007,
  ...chunk008,
  ...chunk009,
  ...chunk010,
  ...chunk011,
  ...chunk012,
  ...chunk013,
  ...chunk014,
  ...chunk015,
  ...chunk016,
  ...chunk017,
  ...chunk018,
  ...chunk019,
  ...chunk020,
  ...chunk021,
  ...chunk022,
  ...chunk023,
  ...chunk024,
  ...chunk025,
  ...chunk026,
  ...chunk027,
  ...chunk028,
  ...chunk029,
  ...chunk030,
  ...chunk031,
  ...chunk032,
  ...chunk033,
  ...chunk034,
  ...chunk035,
  ...chunk036,
  ...chunk037,
  ...chunk038,
  ...chunk039,
  ...chunk040,
  ...chunk041,
  ...chunk042,
  ...chunk043,
  ...chunk044,
  ...chunk045,
  ...chunk046,
  ...chunk047,
  ...chunk048,
  ...chunk049,
  ...chunk050,
  ...chunk051,
  ...chunk052,
  ...chunk053,
  ...chunk054,
  ...chunk055,
  ...chunk056,
  ...chunk057,
  ...chunk058,
  ...chunk059,
  ...chunk060,
  ...chunk061,
  ...chunk062,
  ...chunk063,
  ...chunk064,
  ...chunk065,
  ...chunk066,
  ...chunk067,
  ...chunk068,
  ...chunk069,
  ...chunk070,
  ...chunk071,
  ...chunk072,
  ...chunk073,
  ...chunk074,
  ...chunk075,
  ...chunk076,
  ...chunk077,
  ...chunk078,
  ...chunk079,
  ...chunk080,
  ...chunk081,
  ...chunk082,
  ...chunk083,
  ...chunk084,
  ...chunk085,
  ...chunk086,
  ...chunk087,
  ...chunk088,
  ...chunk089,
  ...chunk090
];

const ADMIN_KEY = Deno.env.get("ADMIN_SURVEY_KEY") ?? "";

// The admin dashboard's own origins, nothing else. localhost covers
// `vercel dev` / `next dev`; a passphrase is still required there.
const ALLOWED_ORIGINS = new Set([
  "https://paybench.org",
  "https://www.paybench.org",
  "https://unsafe-commercial-autonomy.vercel.app",
  "http://localhost:3000",
]);

function corsHeaders(req: Request): Record<string, string> {
  const origin = req.headers.get("origin") ?? "";
  return {
    "Access-Control-Allow-Origin": ALLOWED_ORIGINS.has(origin)
      ? origin
      : "https://paybench.org",
    "Vary": "Origin",
    "Access-Control-Allow-Headers": "x-admin-key, content-type",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
  };
}

// Compare via SHA-256 digests so the comparison cost carries no signal about
// how many leading characters matched.
async function keyMatches(provided: string): Promise<boolean> {
  if (!ADMIN_KEY || !provided) return false;
  const digest = async (value: string) =>
    new Uint8Array(
      await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)),
    );
  const [a, b] = await Promise.all([digest(provided), digest(ADMIN_KEY)]);
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

Deno.serve(async (req) => {
  const cors = corsHeaders(req);
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: cors });
  }

  const json = (status: number, body: unknown) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...cors, "Content-Type": "application/json" },
    });

  if (!ADMIN_KEY) {
    return json(503, { error: "ADMIN_SURVEY_KEY is not configured" });
  }
  if (!(await keyMatches(req.headers.get("x-admin-key") ?? ""))) {
    return json(401, { error: "unauthorized" });
  }
  if (req.method !== "GET") {
    return json(405, { error: "method not allowed" });
  }

  return json(200, { pairs: SCENARIO_PAIRS, count: SCENARIO_PAIRS.length });
});
