// Admin endpoint for the Phase 2 scenario/answer-key snapshot, called by the
// Scenario Explorer at web/app/admin/scenario-explorer. Read-only: the data
// is a static generated file, not a database table, so there is nothing to
// mutate here. The caller authenticates with the same admin passphrase as
// admin-survey-data -- one password for the whole admin surface, no separate
// secret to provision. This file is the source of truth for the deployed
// function -- deploy from the repo, never edit in the dashboard:
//
//   supabase functions deploy admin-scenario-data --no-verify-jwt \
//     --project-ref tethtzycfdplyzvrtknh
//
// scenario_pairs.json is generated by scripts/generate_scenario_explorer_data.py
// (run from the repo root) and must be regenerated + redeployed after any
// change to data/scenario_sets/v2_250_scenarios.md or
// data/answer_keys/v2_constraints.json -- this function only ever serves
// whatever was bundled at the last deploy.

import scenarioPairs from "./scenario_pairs.json" with { type: "json" };

const ADMIN_KEY = Deno.env.get("ADMIN_SURVEY_KEY") ?? "";

// The admin dashboard's own origins, nothing else. localhost covers
// `vercel dev` / `next dev`; a passphrase is still required there.
const ALLOWED_ORIGINS = new Set([
  "https://paybench.org",
  "https://www.paybench.org",
  "https://unsafe-commercial-autonomy.vercel.app",
  "http://localhost:3000",
]);

function corsHeaders(req: Request): Record<string, string> {
  const origin = req.headers.get("origin") ?? "";
  return {
    "Access-Control-Allow-Origin": ALLOWED_ORIGINS.has(origin)
      ? origin
      : "https://paybench.org",
    "Vary": "Origin",
    "Access-Control-Allow-Headers": "x-admin-key, content-type",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
  };
}

// Compare via SHA-256 digests so the comparison cost carries no signal about
// how many leading characters matched.
async function keyMatches(provided: string): Promise<boolean> {
  if (!ADMIN_KEY || !provided) return false;
  const digest = async (value: string) =>
    new Uint8Array(
      await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)),
    );
  const [a, b] = await Promise.all([digest(provided), digest(ADMIN_KEY)]);
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

Deno.serve(async (req) => {
  const cors = corsHeaders(req);
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: cors });
  }

  const json = (status: number, body: unknown) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...cors, "Content-Type": "application/json" },
    });

  if (!ADMIN_KEY) {
    return json(503, { error: "ADMIN_SURVEY_KEY is not configured" });
  }
  if (!(await keyMatches(req.headers.get("x-admin-key") ?? ""))) {
    return json(401, { error: "unauthorized" });
  }
  if (req.method !== "GET") {
    return json(405, { error: "method not allowed" });
  }

  return json(200, scenarioPairs);
});
