"""Snapshot Phase 2's 113 trap/lookalike pairs for the admin Scenario Explorer.

Reads the merged Scenario records the same way app/main.py's
GET /api/phase2/scenarios does, groups the 226 scenarios into 113
trap/lookalike pairs by pair_id, and writes the result as the JSON assets
bundled into the admin-scenario-data Supabase Edge Function. This script is
the only way that function's data gets refreshed -- re-run it and redeploy
after any change to data/scenario_sets/v2_250_scenarios.md or
data/answer_keys/v2_constraints.json.

Split into one file per pair (scenario_pairs.<pair_id>.json, e.g.
scenario_pairs.v2_c12.json, each holding that pair's record) rather than
one ~850KB combined file: the combined file -- and even one file per
category -- is too large for some tooling to read or relay in a single
piece. The filename is the pair's identity, not a position: editing one
scenario changes exactly that pair's file and nothing else, so a diff of
this directory reads as the content change it is. (The previous scheme
packed pairs into sequentially numbered files by size, so any pair growing
or shrinking re-flowed every pair after it into a different file and one
small edit diffed as a near-total rewrite.) index.ts imports every pair
file in canonical pair order and concatenates them.

Pair order is NOT recomputed: it is exactly the first-seen order of pair_id
in load_scenarios() output, i.e. the Markdown file's own row order (category
A to E, ascending pair number within each category, including the numbering
gaps left by the 2026-07-24 twelve-pair cut -- e.g. category B skips to B1,
B3, B4, B5, B10...). Prev/Next in the UI walks this order.

Run from the repo root:  python scripts/generate_scenario_explorer_data.py
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.data import load_scenarios  # noqa: E402
from app.models import model_to_dict  # noqa: E402
from app.phase2 import PHASE2_SCENARIO_SET  # noqa: E402

OUT_DIR = ROOT / "supabase" / "functions" / "admin-scenario-data"
INDEX_PATH = OUT_DIR / "index.ts"
ENFORCEMENT_SCOPE_PATH = ROOT / "data" / "answer_keys" / "phase2_enforcement_scope.json"

# Per-scenario fields folded into each pair's trap/lookalike record, read from
# the committed enforcement-scope projection (data/answer_keys/
# phase2_enforcement_scope.json, generated by generate_phase2_enforcement_scope.py)
# rather than recomputed here -- one sweep, read by both the CLI's phase2-scope
# and this snapshot, so the two can never name a different scope for the same
# scenario. pair_id/pair_role are dropped: the scenario record already carries
# them at the top level.
ENFORCEMENT_FIELDS = ("rail_reachable", "in_enforced_arm", "fires_on", "decisions", "reasons", "offers")

# Category order is not the file-splitting axis (files are one-per-pair,
# independent of category boundaries), but this is still the canonical
# A-to-E order build_pairs() produces and the order Prev/Next walks in the
# UI.
CATEGORY_ORDER = [
    "spend_limits",
    "authorization_scope",
    "consent_and_escalation",
    "privacy_and_disclosure",
    "adversarial_robustness",
]

EXPECTED_CATEGORY_COUNTS = {
    "spend_limits": 25,
    "authorization_scope": 14,
    "consent_and_escalation": 24,
    "privacy_and_disclosure": 25,
    "adversarial_robustness": 25,
}
EXPECTED_PAIR_COUNT = sum(EXPECTED_CATEGORY_COUNTS.values())


def load_enforcement_scope() -> Dict[str, Dict[str, Any]]:
    scope = json.loads(ENFORCEMENT_SCOPE_PATH.read_text(encoding="utf-8"))
    return {
        scenario_id: {field: record[field] for field in ENFORCEMENT_FIELDS}
        for scenario_id, record in scope["scenarios"].items()
    }


def compute_content_hash(record: Dict[str, Any]) -> str:
    """Fingerprint of everything a reviewer sees for this scenario.

    web/lib/scenarioExplorer.ts's isReviewCurrent() compares this against the
    hash a review was stored against (scenario_reviews.content_hash) to decide
    whether that review still describes the current scenario -- so this must
    be called before `content_hash` itself is added to `record`, and it must
    stay a plain, order-independent hash of the whole displayed record (not a
    subset of "important" fields) so no edit -- text, answer key, enforcement
    scope, anything -- can change under a review without being caught.
    """
    canonical = json.dumps(record, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def build_pairs() -> List[Dict[str, Any]]:
    enforcement = load_enforcement_scope()
    records = [model_to_dict(s) for s in load_scenarios(PHASE2_SCENARIO_SET)]
    for record in records:
        # source_line is live-parse provenance, not scenario content: any prose
        # edit above the tables in the scenario-set markdown renumbers every
        # row, which used to rewrite all 113 committed pair files (and, worse,
        # churn their content hashes, resetting review statuses over a comment
        # change). Dropped from the committed output; source_file remains.
        record.get("payment_policy", {}).pop("source_line", None)
        record["enforcement"] = enforcement[record["scenario_id"]]
        record["content_hash"] = compute_content_hash(record)

    grouped: Dict[str, Dict[str, Dict[str, Any]]] = {}
    order: List[str] = []
    for record in records:
        pair_id = record["pair_id"]
        role = record["pair_role"]
        if pair_id not in grouped:
            grouped[pair_id] = {}
            order.append(pair_id)
        if role in grouped[pair_id]:
            raise ValueError(f"Duplicate {role!r} for pair_id {pair_id!r}")
        grouped[pair_id][role] = record

    pairs: List[Dict[str, Any]] = []
    for pair_id in order:
        roles = grouped[pair_id]
        missing = {"trap", "lookalike"} - roles.keys()
        if missing:
            raise ValueError(f"Pair {pair_id!r} is missing role(s): {sorted(missing)}")
        trap = roles["trap"]
        pairs.append(
            {
                "pair_id": pair_id,
                "pair_label": trap["environment"]["pair"],
                "category": trap["category"],
                "trap": trap,
                "lookalike": roles["lookalike"],
            }
        )

    if len(pairs) != EXPECTED_PAIR_COUNT:
        raise ValueError(f"Expected {EXPECTED_PAIR_COUNT} pairs, got {len(pairs)}")

    counts: Dict[str, int] = {}
    for pair in pairs:
        counts[pair["category"]] = counts.get(pair["category"], 0) + 1
    if counts != EXPECTED_CATEGORY_COUNTS:
        raise ValueError(f"Category counts drifted from expectations: {counts}")

    return pairs


def pair_filename(pair_id: str) -> str:
    return f"scenario_pairs.{pair_id}.json"


def pair_import_name(pair_id: str) -> str:
    return f"pair_{pair_id}"


def write_pair_files(pairs: List[Dict[str, Any]], out_dir: Path) -> List[Path]:
    # Clear any pair files from a previous run first, so a removed or renamed
    # pair never leaves a stale, no-longer-imported file behind for a human
    # to wonder about.
    for stale in out_dir.glob("scenario_pairs.*.json"):
        stale.unlink()

    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for pair in pairs:
        path = out_dir / pair_filename(pair["pair_id"])
        path.write_text(json.dumps(pair, indent=2) + "\n", encoding="utf-8")
        written.append(path)
    return written


def sync_index_imports(index_path: Path, pairs: List[Dict[str, Any]]) -> None:
    """Keep the Edge Function's imports in step with the generated pair files.

    The import list, in build_pairs() order, is what preserves the canonical
    A-to-E pair order the UI's Prev/Next walks -- the filenames themselves
    sort lexicographically (v2_a1, v2_a10, v2_a11...), so the order lives
    here, not in the directory listing.
    """
    source = index_path.read_text(encoding="utf-8")
    imports = "\n".join(
        f'import {pair_import_name(p["pair_id"])} from "./{pair_filename(p["pair_id"])}"'
        f' with {{ type: "json" }};'
        for p in pairs
    )
    entries = ",\n".join(f"  {pair_import_name(p['pair_id'])}" for p in pairs)
    replacement = f"{imports}\n\nconst SCENARIO_PAIRS = [\n{entries}\n];"
    updated, count = re.subn(
        r'import \w+ from "\./scenario_pairs\..*?\n\nconst SCENARIO_PAIRS = \[.*?\n\];',
        replacement,
        source,
        count=1,
        flags=re.DOTALL,
    )
    if count != 1:
        raise ValueError(f"Could not locate generated import block in {index_path}")
    index_path.write_text(updated, encoding="utf-8")


def main(out_dir: Path = OUT_DIR) -> None:
    pairs = build_pairs()
    written = write_pair_files(pairs, out_dir)
    if out_dir.resolve() == OUT_DIR.resolve():
        sync_index_imports(INDEX_PATH, pairs)
    print(f"Wrote {len(pairs)} pairs across {len(written)} pair files to {out_dir}")


if __name__ == "__main__":
    main()
